resource_group_name      = "rg-khushi-qr-generator-01"
location                 = "West Europe"
storage_account_name     = "sakhushiqrfuncapp01"
service_plan_name        = "as-plan-khushi-funcapp-01"
function_app_name        = "functionapp-khushi-01"
application_insight_name = "appinsight-khushi-01"
