name: Deploy Azure Infra for QR Fucntion App Project

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select Action (apply or destroy)"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

jobs:
  Infra-deployment-function-app:
    runs-on: ubuntu-latest # Agent VM where code gets build
    environment: dev 

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      BACKEND_STORAGE_ACC: sakhushitfstate01
      ENV: dev

    defaults:
      run:
        working-directory: "./Infra"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3 # git clone in Agent VM

    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init -backend-config "key=qr-generator-proj/${{ env.ENV }}/terraform.tfstate" -backend-config="access_key=${{ secrets.TF_BackendConfig_Access_Key }}"

    - name: Terraform Format & Validate
      run: |
        terraform fmt
        terraform validate

    - name: Terraform Plan
      run: terraform plan -var-file="env/${{ env.ENV }}.tfvars"

    - name: Terraform Apply
      if: ${{ github.event.inputs.action == 'apply' }}
      run: terraform apply -var-file="env/${{ env.ENV }}.tfvars" -auto-approve

    - name: Terraform Destroy
      if: ${{ github.event.inputs.action == 'destroy' }}
      run: terraform destroy -var-file="env/${{ env.ENV }}.tfvars" -auto-approve